### ISSUE TITLE
Does opensse-schemes support centos7?

### ISSUE THREAD

**Issue by OpenJZ** [OpenSSE/opensse-schemes#13]
I try to build opensse-schemes on centos7, but I met some problems, what should I do? 
The problems look like this, "In file included from /home/swj/research/build/opensse-schemes/third_party/crypto/src/ppke/util.hpp:3:0,
                 from /home/swj/research/build/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:11,
                 from /home/swj/research/build/opensse-schemes/third_party/crypto/src/puncturable_enc.cpp:23:
/home/swj/research/build/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function 'bool relicxx::operator==(const relicxx::ZR&, const relicxx::ZR&)':
/home/swj/research/build/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:218:33: error: 'RLC_EQ' was not declared in this scope
         if (bn_cmp(x.z, y.z) == RLC_EQ) {"

**Comment by rbost** [comment]
Hi @OpenJZ,

This is not an issue with CentOS, but with Relic.
The API of Relic is not super stable, changed recently, and the compilation of old versions of the cryptographic toolkit subsequently fails. However, this has recently been fixed in [v0.3.2 of crypto-tk](https://github.com/OpenSSE/crypto-tk/releases/tag/v0.3.2). Yet, I did not have the time to update the dependency in `opensse-schemes`.

The solution to your problem should be simple (successfully tested on a clean clone of the repo):
* in your terminal, go to the `third-party/crypto` directory (make sure you are **not** in the `build/third-party/crypto` directory, otherwise the solution will not work);
* update the git submodule by running `git checkout v0.3.2`;
* (re)build.

This should do it.
